import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-midstream-gathering-processing-deduction-audit",
  "engine": "recovery",
  "title": "Midstream Gathering & Processing Deduction Audit",
  "shortTitle": "Midstream Gathering and Processing Deduction Audit",
  "tagline": "Audit midstream volume loss, fuel, shrink, processing fees, NGL yields, and netback settlement calculations.",
  "industry": "Oil & Gas Revenue Assurance",
  "buyer": "Producers and mineral owners",
  "uiPort": 4714,
  "apiPort": 5714,
  "accent": "#7e22ce",
  "currency": "USD",
  "primaryOutcome": "Midstream Gathering & Processing Deduction Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect gathering and processing agreements, meter volumes, quality, shrink, fuel, NGL yields, residue gas, fees, index prices, statements, and cash in one accountable workflow. Audit midstream volume loss, fuel, shrink, processing fees, NGL yields, and netback settlement calculations.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Midstream Gathering & Processing Deduction Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("midstream-contract-library","MGP01","Midstream contract library","Execute midstream contract library using gathering and processing agreements, meter volumes, quality, shrink, fuel, NGL yields, residue gas, fees, index prices, statements, and cash.","Produce a governed midstream contract library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Midstream System / Production Month","text","Midstream System / Production Month · Standard Case"],["caseReference","Midstream contract library Reference","text","MGP01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1483750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1795338],["domainDriver","Deduction Type","select","Gathering",["Gathering","Processing","Fuel shrink"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Midstream contract library case","Meter statement ingestion case","Volume balancing case","Gas quality adjustment case","Fuel use calculation case"]}),
feature("meter-statement-ingestion","MGP02","Meter statement ingestion","Execute meter statement ingestion using gathering and processing agreements, meter volumes, quality, shrink, fuel, NGL yields, residue gas, fees, index prices, statements, and cash.","Produce a governed meter statement ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Midstream System / Production Month","text","Midstream System / Production Month · Standard Case"],["caseReference","Meter statement ingestion Reference","text","MGP02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1483750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1795338],["domainDriver","Deduction Type","select","Gathering",["Gathering","Processing","Fuel shrink"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Midstream contract library case","Meter statement ingestion case","Volume balancing case","Gas quality adjustment case","Fuel use calculation case"]}),
feature("volume-balancing","MGP03","Volume balancing","Execute volume balancing using gathering and processing agreements, meter volumes, quality, shrink, fuel, NGL yields, residue gas, fees, index prices, statements, and cash.","Produce a governed volume balancing decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Midstream System / Production Month","text","Midstream System / Production Month · Standard Case"],["caseReference","Volume balancing Reference","text","MGP03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1483750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1795338],["domainDriver","Deduction Type","select","Gathering",["Gathering","Processing","Fuel shrink"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Midstream contract library case","Meter statement ingestion case","Volume balancing case","Gas quality adjustment case","Fuel use calculation case"]}),
feature("gas-quality-adjustment","MGP04","Gas quality adjustment","Execute gas quality adjustment using gathering and processing agreements, meter volumes, quality, shrink, fuel, NGL yields, residue gas, fees, index prices, statements, and cash.","Produce a governed gas quality adjustment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Midstream System / Production Month","text","Midstream System / Production Month · Standard Case"],["caseReference","Gas quality adjustment Reference","text","MGP04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1483750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1795338],["domainDriver","Deduction Type","select","Gathering",["Gathering","Processing","Fuel shrink"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Midstream contract library case","Meter statement ingestion case","Volume balancing case","Gas quality adjustment case","Fuel use calculation case"]}),
feature("fuel-use-calculation","MGP05","Fuel use calculation","Execute fuel use calculation using gathering and processing agreements, meter volumes, quality, shrink, fuel, NGL yields, residue gas, fees, index prices, statements, and cash.","Produce a governed fuel use calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Midstream System / Production Month","text","Midstream System / Production Month · Standard Case"],["caseReference","Fuel use calculation Reference","text","MGP05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1483750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1795338],["domainDriver","Deduction Type","select","Gathering",["Gathering","Processing","Fuel shrink"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Midstream contract library case","Meter statement ingestion case","Volume balancing case","Gas quality adjustment case","Fuel use calculation case"]}),
feature("shrink-calculation","MGP06","Shrink calculation","Execute shrink calculation using gathering and processing agreements, meter volumes, quality, shrink, fuel, NGL yields, residue gas, fees, index prices, statements, and cash.","Produce a governed shrink calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Midstream System / Production Month","text","Midstream System / Production Month · Standard Case"],["caseReference","Shrink calculation Reference","text","MGP06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1483750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1795338],["domainDriver","Deduction Type","select","Gathering",["Gathering","Processing","Fuel shrink"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Midstream contract library case","Meter statement ingestion case","Volume balancing case","Gas quality adjustment case","Fuel use calculation case"]}),
feature("processing-fee-validation","MGP07","Processing fee validation","Execute processing fee validation using gathering and processing agreements, meter volumes, quality, shrink, fuel, NGL yields, residue gas, fees, index prices, statements, and cash.","Produce a governed processing fee validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Midstream System / Production Month","text","Midstream System / Production Month · Standard Case"],["caseReference","Processing fee validation Reference","text","MGP07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1483750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1795338],["domainDriver","Deduction Type","select","Gathering",["Gathering","Processing","Fuel shrink"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Midstream contract library case","Meter statement ingestion case","Volume balancing case","Gas quality adjustment case","Fuel use calculation case"]}),
feature("ngl-yield-calculation","MGP08","NGL yield calculation","Execute ngl yield calculation using gathering and processing agreements, meter volumes, quality, shrink, fuel, NGL yields, residue gas, fees, index prices, statements, and cash.","Produce a governed ngl yield calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Midstream System / Production Month","text","Midstream System / Production Month · Standard Case"],["caseReference","NGL yield calculation Reference","text","MGP08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1483750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1795338],["domainDriver","Deduction Type","select","Gathering",["Gathering","Processing","Fuel shrink"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Midstream contract library case","Meter statement ingestion case","Volume balancing case","Gas quality adjustment case","Fuel use calculation case"]}),
feature("ngl-price-validation","MGP09","NGL price validation","Execute ngl price validation using gathering and processing agreements, meter volumes, quality, shrink, fuel, NGL yields, residue gas, fees, index prices, statements, and cash.","Produce a governed ngl price validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Midstream System / Production Month","text","Midstream System / Production Month · Standard Case"],["caseReference","NGL price validation Reference","text","MGP09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1483750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1795338],["domainDriver","Deduction Type","select","Gathering",["Gathering","Processing","Fuel shrink"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Midstream contract library case","Meter statement ingestion case","Volume balancing case","Gas quality adjustment case","Fuel use calculation case"]}),
feature("residue-gas-settlement","MGP10","Residue gas settlement","Execute residue gas settlement using gathering and processing agreements, meter volumes, quality, shrink, fuel, NGL yields, residue gas, fees, index prices, statements, and cash.","Produce a governed residue gas settlement decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Midstream System / Production Month","text","Midstream System / Production Month · Standard Case"],["caseReference","Residue gas settlement Reference","text","MGP10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1483750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1795338],["domainDriver","Deduction Type","select","Gathering",["Gathering","Processing","Fuel shrink"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Midstream contract library case","Meter statement ingestion case","Volume balancing case","Gas quality adjustment case","Fuel use calculation case"]}),
feature("gathering-fee-audit","MGP11","Gathering fee audit","Execute gathering fee audit using gathering and processing agreements, meter volumes, quality, shrink, fuel, NGL yields, residue gas, fees, index prices, statements, and cash.","Produce a governed gathering fee audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Midstream System / Production Month","text","Midstream System / Production Month · Standard Case"],["caseReference","Gathering fee audit Reference","text","MGP11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1483750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1795338],["domainDriver","Deduction Type","select","Gathering",["Gathering","Processing","Fuel shrink"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Midstream contract library case","Meter statement ingestion case","Volume balancing case","Gas quality adjustment case","Fuel use calculation case"]}),
feature("netback-reconstruction","MGP12","Netback reconstruction","Execute netback reconstruction using gathering and processing agreements, meter volumes, quality, shrink, fuel, NGL yields, residue gas, fees, index prices, statements, and cash.","Produce a governed netback reconstruction decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Midstream System / Production Month","text","Midstream System / Production Month · Standard Case"],["caseReference","Netback reconstruction Reference","text","MGP12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1483750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1795338],["domainDriver","Deduction Type","select","Gathering",["Gathering","Processing","Fuel shrink"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Midstream contract library case","Meter statement ingestion case","Volume balancing case","Gas quality adjustment case","Fuel use calculation case"]}),
feature("midstream-dispute-workflow","MGP13","Midstream dispute workflow","Execute midstream dispute workflow using gathering and processing agreements, meter volumes, quality, shrink, fuel, NGL yields, residue gas, fees, index prices, statements, and cash.","Produce a governed midstream dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Midstream System / Production Month","text","Midstream System / Production Month · Standard Case"],["caseReference","Midstream dispute workflow Reference","text","MGP13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1483750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1795338],["domainDriver","Deduction Type","select","Gathering",["Gathering","Processing","Fuel shrink"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Midstream contract library case","Meter statement ingestion case","Volume balancing case","Gas quality adjustment case","Fuel use calculation case"]}),
feature("cash-reconciliation","MGP14","Cash reconciliation","Execute cash reconciliation using gathering and processing agreements, meter volumes, quality, shrink, fuel, NGL yields, residue gas, fees, index prices, statements, and cash.","Produce a governed cash reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Midstream System / Production Month","text","Midstream System / Production Month · Standard Case"],["caseReference","Cash reconciliation Reference","text","MGP14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1483750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1795338],["domainDriver","Deduction Type","select","Gathering",["Gathering","Processing","Fuel shrink"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Midstream contract library case","Meter statement ingestion case","Volume balancing case","Gas quality adjustment case","Fuel use calculation case"]}),
feature("system-plant-analytics","MGP15","System plant analytics","Execute system plant analytics using gathering and processing agreements, meter volumes, quality, shrink, fuel, NGL yields, residue gas, fees, index prices, statements, and cash.","Produce a governed system plant analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Midstream System / Production Month","text","Midstream System / Production Month · Standard Case"],["caseReference","System plant analytics Reference","text","MGP15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1483750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1795338],["domainDriver","Deduction Type","select","Gathering",["Gathering","Processing","Fuel shrink"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Midstream contract library case","Meter statement ingestion case","Volume balancing case","Gas quality adjustment case","Fuel use calculation case"]})
]);
